# Generated by Django 4.1.5 on 2023-01-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimg', models.ImageField(upload_to='images/')),
                ('addcategory', models.CharField(max_length=15)),
                ('productname', models.CharField(max_length=25)),
                ('productprice', models.IntegerField()),
                ('productquantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addcategory', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15)),
                ('pword', models.CharField(max_length=20)),
                ('rights', models.CharField(default='User', max_length=25)),
            ],
        ),
    ]
