# Generated by Django 4.1.5 on 2023-01-28 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('staddress', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('ph', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesno', models.IntegerField()),
                ('sdate', models.DateField(default=datetime.date.today)),
                ('custid', models.IntegerField()),
                ('cname', models.CharField(max_length=25)),
                ('total', models.IntegerField()),
                ('cardno', models.IntegerField()),
                ('expdate', models.CharField(max_length=20)),
                ('ccv', models.IntegerField()),
                ('carduser', models.CharField(max_length=25)),
                ('status', models.CharField(default='o', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='salessub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesno', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('pname', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField()),
                ('serialno', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
